[options]
db_host = postgres
db_port = 5432
db_user = odoo
db_password = odoo123
db_name = False
addons_path = /app/addons,/app/odoo/addons,/app/custom_addons
data_dir = /var/lib/odoo
limit_time_cpu = 600
limit_time_real = 1200
admin_passwd = qba123@#

dev_mode = reload,xml,qweb

# workers = 2
# max_cron_threads = 1
